version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
  historytable:
    image: ${DOCKER_REGISTRY}historytable
    build:
      context: .
      dockerfile: HistoryTable/Dockerfile
    depends_on:
      - sql.data
